### PR TITLE
Send Stdin EOF on Close()

### LINKED ISSUE #104: CommandWriter Close() infinite loop
https://github.com/masterzen/winrm/blob/master/command.go#L227-L230

```go
// Close method wrapper
// commandWriter implements io.Closer interface
func (w *commandWriter) Close() error {
	w.eof = true
	return w.Close()
}
```

I'm not a go-wizard, but doesn't this create an infinite loop and cause a stack overflow panic? I got this:

```
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow

runtime stack:
runtime.throw(0x1611bb0, 0xe)
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/panic.go:774 +0x72
runtime.newstack()
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/stack.go:1046 +0x6e9
runtime.morestack()
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/asm_amd64.s:449 +0x8f

goroutine 173 [running]:
github.com/masterzen/winrm.(*commandWriter).Close(0xc00023ecc0, 0x0, 0x0)
	/Users/kimmo/Projects/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20200518133226-8ad2e8823256/command.go:227 +0x52 fp=0xc02085a360 sp=0xc02085a358 pc=0x1404082
github.com/masterzen/winrm.(*commandWriter).Close(0xc00023ecc0, 0x0, 0x0)
	/Users/kimmo/Projects/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20200518133226-8ad2e8823256/command.go:229 +0x2f fp=0xc02085a388 sp=0xc02085a360 pc=0x140405f
github.com/masterzen/winrm.(*commandWriter).Close(0xc00023ecc0, 0x0, 0x0)
	/Users/kimmo/Projects/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20200518133226-8ad2e8823256/command.go:229 +0x2f fp=0xc02085a3b0 sp=0xc02085a388 pc=0x140405f
github.com/masterzen/winrm.(*commandWriter).Close(0xc00023ecc0, 0x0, 0x0)
	/Users/kimmo/Projects/go/pkg/mod/github.com/masterzen/winrm@v0.0.0-20200518133226-8ad2e8823256/command.go:229 +0x2f fp=0xc02085a3d8 sp=0xc02085a3b0 pc=0x140405f
github.com/masterzen/winrm.(*commandWriter).Close(0xc00023ecc0, 0x0, 0x0)

...and so on
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #104
Closes #82 

Sets `@End = true` in the input stream when closing Stdin or sending a single string instead of a stream.

### CODE REVIEW

**Comment by kke** [comment]
@masterzen PTAL

File: client.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ func NewClientWithParameters(endpoint *Endpoint, user, password string, params *
 		url:        endpoint.url(),
 		useHTTPS:   endpoint.HTTPS,
 		// default transport
-		http: &clientRequest{ dial:params.Dial },
+		http: &clientRequest{dial: params.Dial},
```
Comment (kke) [inline client.go:49]: Unrelated, my editor's auto-format just won't let me save it unchanged :)

File: request_test.go [hunk 2]
```diff
@@ -7,8 +7,8 @@ import (
 	"github.com/ChrisTrenkamp/goxpath"
 	"github.com/ChrisTrenkamp/goxpath/tree"
 	"github.com/ChrisTrenkamp/goxpath/tree/xmltree"
-	"github.com/masterzen/winrm/soap"
 	"github.com/masterzen/simplexml/dom"
+	"github.com/masterzen/winrm/soap"
```
Comment (kke) [inline request_test.go:11]: Again unrealted, my autoformat reorders the imports..

**Comment by kke** [comment]
This appears to be quite similar to #82

File: request.go [hunk 3]
```diff
@@ -131,6 +131,9 @@ func NewSendInputRequest(uri, shellId, commandId string, input []byte, params *P
 	streams.SetAttr("Name", "stdin")
 	streams.SetAttr("CommandId", commandId)
 	streams.SetContent(content)
+	if eof {
+		streams.SetAttr("End", "true")
```
Comment (masterzen) [inline request.go:135]: 👍

**Comment by masterzen** [comment]
@kke I had some time tonight so I took your code and modified to respect a bit more the `io.Writer` and `io.Closer` interface and make it a bit more idiomatic.
Please pull my changes, and check that it still works for your use case.
I'll fix the tests tomorrow, and if everything works, I'll merge our work.

Again, thanks for your help and code :)

**Comment by kke** [comment]
Thanks for the comments, I'll look at them closer tomorrow morning (which is 14 hours from now in local time) and test it out.

**Comment by masterzen** [comment]
@kke yes, just grab the changes and test them for your use case.
If this is successful I will be able to merge the PR (I might add a few tests potentially).

**Comment by kke** [comment]
Seems to work now.

My `ExecCmd` function looks like:

```go
// ExecCmd executes a command on the host
func (c *Connection) ExecCmd(cmd string, stdin string, streamStdout bool, sensitiveCommand bool) error {
	shell, err := c.client.CreateShell()
	if err != nil {
		return err
	}

	if !sensitiveCommand {
		log.Debugf("%s: executing command: %s", c.Address, cmd)
	}

	command, err := shell.Execute(cmd)
	if err != nil {
		return err
	}

	if stdin != "" {
		if !sensitiveCommand {
			log.Debugf("%s: writing data to command stdin: %s", c.Address, stdin)
		}
		go func() {
			command.Stdin.Write([]byte(stdin))
			command.Stdin.Close()
		}()
	}

	multiReader := io.MultiReader(command.Stdout, command.Stderr)
	outputScanner := bufio.NewScanner(multiReader)

	for outputScanner.Scan() {
		if streamStdout {
			log.Infof("%s:  %s", c.Address, outputScanner.Text())
		} else {
			log.Debugf("%s:  %s", c.Address, outputScanner.Text())
		}
	}
	if err := outputScanner.Err(); err != nil {
		log.Errorf("%s:  %s", c.Address, err.Error())
	}

	command.Wait()
	shell.Close()

	if command.ExitCode() > 0 {
		return fmt.Errorf("%s: command failed", c.Address)
	}

	return nil
}
```

This seems to do what I want, it correctly feeds stuff to stdin and logs results as they happen.

If I remove the `command.Stdin.Close()`, it hangs and stays waiting for the stream to close, which makes me believe it will probably even work for interactive prompts during execution.

**Comment by masterzen** [comment]
@kke you might want to add a `command.Close()` right before the `shell.Close()` . I don't think it is strictly necessary since I suppose that closing the shell would therefore close the command, but it's cleaner.
