### PR TITLE
Fix #48 - OperationTimeout aborts the current command

### LINKED ISSUE #48: "http error: 500" on latest master
As part of our deployment process, we build and deploy the latest winrm version.  We've noticed that master now seems to error with "http error: 500" when we're doing long running commands (usually after about 70 seconds or so).

This previously didn't happen, and it doesn't happen on versions of WinRM that only have these options (not sure which commit this was built from):

```
Usage of winrm:
  -hostname="localhost": winrm host
  -password="vagrant": winrm admin password
  -port=5985: winrm port
  -username="vagrant": winrm admin username
```

I'm sure we've been running newer versions than this, but this was the version of WinRM I could find since I needed to restore service quickly.

### PR DESCRIPTION
**Pull request by masterzen**
Since PR #25 winrm is now unfortunately reporting up `OperationTimeout` errors when the command doesn't output anything, and aborting processing.

This changeset is PR #26 by @pecigonzalo which I rebased in order to be able to merge it on top of current master.

### CODE REVIEW

**Comment by pecigonzalo** [comment]
Sorry i was unable to process this, i have limited internet access for the time being

File: winrm/client.go [hunk 1]
```diff
@@ -18,10 +19,22 @@ type Client struct {
...
 	useHTTPS  bool
 	url       string
+	err       error
 	http      HttpPost
 	transport http.RoundTripper
 }
 
+// Map of known terminating errors, this will be utilized for returning error codes and error messages on
+// fatal errors
+var errorCode = map[string]int{
```
Comment (hoenirvili) [inline winrm/client.go]: I think instead of using that much memory just to make map of errors , will be better to make a separated file with declared errors like:

```go
var (
  errEOF = errors.New("A connection terminated unexpectedly, error while sending request to endpoint")
  errorTimeout = errors.New("Operation timeout because there was no command output")
)
```
Go has these types of error declarations inside stdlib for example witch in my opinion is much more nicer than using a hole map.

Comment (pecigonzalo) [inline winrm/client.go]: That was the initial solution and it was suggested to use a map.

Comment (masterzen) [inline winrm/client.go]: Yes, I remember I asked @pecigonzalo to make the change. But you're right it might be more golang idiomatic the other way. I'll change that.

**Comment by masterzen** [comment]
I've refactored the error handling so we don't have an error map anymore.
@hoenirvili feel free to review this PR, so that I can merge it.

File: winrm/client.go [hunk 2]
```diff
@@ -107,49 +114,84 @@ func (client *Client) NewShell(shellID string) *Shell {
...
+
+// Check if we need to return an ExitCode
+func (client *Client) ExitCode(cmd *Command) (exitCode int) {
+	if cmd != nil {
+		if cmd.ExitCode() != 0 {
+			return cmd.exitCode
+		}
+	}
+	exitCode, _ = client.check()
+	return exitCode
```
Comment (hoenirvili) [inline winrm/client.go]: If you give the return besides his type a name  it automatically **allocs on the stack** that *var* of that *type* (in our case **int**) so it's a little **redundant** to use ```return nameParam``` and you can write this as a **naked** return ``` return ``` but naked returns are *bad* and it's not *idiomatic* way to do this and it's a little difficult to review for other contribuitors the code especially for longer functions and I suggest to eliminate the return name var and just specify the type of return and alloc that var somewhere in the func semantic and return it like ``` return scopeVar ```.
A good plus for specifing a name on the return param is just for documentation purpose.
I hope you @masterzen  will decide what is better, A good point is for the future it will be very good to make a **.md** document with code guidelines this way we will eliminate inconsistency in the code and make a much more cleaner syntactically.

File: winrm/errors.go [hunk 3]
```diff
@@ -0,0 +1,33 @@
+package winrm
+
+import (
+	"fmt"
+	"strings"
+)
+
+type ServerError struct {
```
Comment (hoenirvili) [inline winrm/errors.go]: I think we don't need multiple return struct types and I think it's wrong that we added in the Client struct the err attribute.What I'm seeing  is ,  these types in order to be compatible with the error type in go it needs to implement the Error interface/contract.
```go
type error interface {
    Error() string
}
```
As I'm seeing this package needs desperately a **log** system or a good error descriptive general **error type**. Also it needs to separate the business logic and the error logic clearly and inserting that **err** field in the **client** type  is not in **my opinion** a good way.

File: winrm/client.go [hunk 4]
```diff
@@ -18,10 +18,16 @@ type Client struct {
 	password  string
 	useHTTPS  bool
 	url       string
+	err       error
 	http      HttpPost
 	transport http.RoundTripper
 }
 
+type WinRMError struct {
```
Comment (hoenirvili) [inline winrm/client.go]: This should implement the **Error interface** rather than the **Client**.
Check the last comment.

File: winrm/client.go (hunk 2 above)
Comment (masterzen) [inline winrm/client.go]: @hoenirvili ok, good to know.

We can make those functions not using named return variables, if that's the better way (I'm not an experienced Go dev as you might have noticed).

Regarding documenting our guide style, I'm not against it, but my experience shows that trying to adhere to very strict guidelines really reduces the number of people that are willing to help on a project. And I don't have the bandwidth to modify every pull request to adhere to a specific guide line.

Would there be a golang linter we can use that would check those kind of things?

Meanwhile I will modify this patch to eleminate named return vars where it's not needed.

File: winrm/client.go (hunk 4 above)
Comment (masterzen) [inline winrm/client.go]: This is a left over I forgot to remove. All the errors are defined in `errors.go`, and only returned as pure Go `error`.

File: winrm/errors.go (hunk 3 above)
Comment (masterzen) [inline winrm/errors.go]: It's not a return struct, it's just there to catalog errors that the winrm server can return and that we should return to the end-user (or not).

I do agree that using the `Client` as the relay for errors when running a command is a bad practice. We already have an `err` in the `Command`, this should be enough.

I'm going to see how I can rewrite the patch to eliminate this.

Comment (masterzen) [inline winrm/errors.go]: re-reading the original patch by @pecigonzalo , the idea behind adding the `err` in the `Client` is that if something went wrong at the http level, then that means this client won't be able to run any new commands, so it marks it as "errored" and aborts.

What we really need right now, is survive to `OperationTimeout` which will fix #48. I think we can get the other feature of the patch (ie mark a client as 'aborted' if there's an EOF), by just marking the `Client` aborted (which would require only one boolean field).

I'm going to keep only the first part of this patch, fix the `OperationTimeout` survival. Then I'll see how we can fix the original problem this patch wanted to fix (allow to reboot a VM or run `net stop`). I'll force re-push this PR as soon as I have something ready.

**Comment by masterzen** [comment]
I've pushed a new version.
Sorry @pecigonzalo I had to remove most of your code in the process, since adding the `error` in the `Client` wasn't a good idea.
I tested rebooting the machine works (with code akin to what Packer is doing now), and this still works. This also fixes #48 (which was the primary goal).
It also adds more tests to make sure we won't break again support for `OperationTimeout`. It also returns an error and command non-zero exit code in case of EOF during a WinRM transaction (which can happen during a server reboot).

I think this should be merged ASAP, and if we need to rework to support a different scheme of server reboot, we can work again on this in the future.

**Comment by masterzen** [comment]
And interestingly the tests are not passing on Go 1.6, while they pass on Go 1.5 and on my machine (with Go 1.6).

**Comment by hoenirvili** [comment]
So I think this PR should finally be merged.
