### PR TITLE
Fix http/timeout while waiting for command output

### LINKED ISSUE #147: Reading the output of long running commands gives net/http: timeout
If you execute a long running command that doesn't output for a while and keep reading the stdout/stderr, you get:

`unknown error Post "https://127.0.0.1:5986/wsman": net/http: timeout awaiting response headers"`

I suppose this bit at command.go is supposed to catch that:

```go
	response, err := c.client.sendRequest(request)
	if err != nil {
		if strings.Contains(err.Error(), "OperationTimeout") {
			// Operation timeout because there was no command output
			return false, err
		}
		if strings.Contains(err.Error(), "EOF") {
			c.exitCode = 16001
		}

		c.Stderr.write.CloseWithError(err)
		c.Stdout.write.CloseWithError(err)
		return true, err
	}
```

But as we can see in the error message, the matcher against `OperationTimeout` does not seem to be correct, maybe it once was.

### PR DESCRIPTION
**Pull request by kke**
Fixes #147 

In addition to the existing SOAP OperationTimeout, this PR makes the output retriever check if the error returned from the HTTP request is a http/timeout, which needs to be handled the same way.

### CODE REVIEW

File: command.go [hunk 1]
```diff
@@ -142,6 +146,10 @@ func (c *Command) slurpAllOutput() (bool, error) {
 
 	response, err := c.client.sendRequest(request)
 	if err != nil {
+		if errWithTimeout, ok := err.(errWithTimeout); ok && errWithTimeout.Timeout() {
```
Comment (masterzen) [inline command.go:149]: I'm wondering if we shouldn't instead use `url.Error` instead of declaring our own interface, and using `errors.As`:

```suggestion
		var errWithTimeout url.Error
		if errors.As(err, &errWithTimeout) && errWithTimeout.Timeout() {
```

This seems to be more idiomatic.

Comment (kke) [reply command.go:149]: Seems to do the same thing yes

**Review by masterzen — APPROVED** [review]
LGTM
